### PR TITLE
feature/pablo-iglesias

### PR DESCRIPTION
**Pull request by pablo-iglesias**
My first commit is just about compliance with the prior acceptance criteria, reflecting that criteria in the test cases.

### CODE REVIEW

**Comment by pablo-iglesias** [comment]
If you watch the commit a8a8308 you will notice that I was forced to modify a column annotation in the Tweet entity in order to switch one of its fields from a VARCHAR to a CLOB, because a tweet with embedded links is potentially very long. 

Now, because most tweets will likely fit into a VARCHAR I could provide an abstraction by which the text is stored in a separate table only when it is too long. Do you want me to do so?

**Comment by pablo-iglesias** [comment]
A little fix over the base code. 
If the call to persist triggered an exception the metric would not get incremented.

**Comment by pablo-iglesias** [comment]
Am I supposed to ask what does pre2015MigrationStatus mean ?

**Comment by pablo-iglesias** [comment]
I have not provided unit tests for the repository because it is already covered 100% by the preexisting tests, but I could do it on demand if needed.

**Comment by pablo-iglesias** [comment]
I am done

**Comment by naxhh** [comment]
Hi @pablo-iglesias sorry for the lest response!

Good call regarding pre2015MigrationStatus, but you can keep the code as it's current state 😄 

I'll start the review then!

**Pull request closed without merging**
