### PR TITLE
Javier Gomez's Backend Test

### PR DESCRIPTION
**Pull request by javier-gomez-github**

### CODE REVIEW

**Comment by javier-gomez-github** [comment]
Hi all, my Pull Request is ready to be reviewed.
Please feel free to review it and comment. I'll be adding my notes in the PR.

Thanks!

**Comment by javier-gomez-github** [comment]
Hi guys, I have done a refactor that is available in another branch, because I'm not sure if I'm allowed to push it since my due date was on Friday. 
Please let me know if I can merge these changes too. The branch is this one: https://github.com/javier-gomez-github/ms-fc--backend-test/tree/jgomez-refactor

Thanks!

**Comment by kmruiz** [comment]
Hi Javier,

please add those changes to this branch. We will review this PR during this week.

We'll ping you.

Thanks for your time!

**Comment by javier-gomez-github** [comment]
Hi @kmruiz, 
I've added the refactor to this PR.

Thanks!

**Pull request closed without merging**
