### PR TITLE
Q&A

### PR DESCRIPTION
**Pull request by olivernoguera**
Hi,

I have a question of requiriments :

1.  In requeriment "list of published Tweets" , I must show a ordered list of tweets by date descending.But technical requiriments says "API contracts can't be changed or modified any way." I undertand date fields are only internal, is correct?.

I think I undertand all requiriments, but I will start to development this evening, I think , today I will finish.

Have I  a limit of commits in my remote repository? I prefer serveral microcommits to one huge commit.
When I fisnish , I will open a new pullRequest with commits merge?

I look forward to hearing from you,

Oliver Noguera

### CODE REVIEW

**Comment by guatebus** [comment]
Hello Oliver, answering your questions:

1. you are correct, respecting the API contract means not exposing dates
2. you are free to organize how you push your work, there is no max number of commits allowed
3. how your application handles nonexistent tweet ids is up to you; you should design it to be as "correct" (as defined by general best-practices) as possible.

Thanks for your questions and be sure to ask anything else if you need.

**Comment by FernandoAbogado** [comment]
Hi Oliver,
sorry but it's not very clear what are we supposed to do now.
Should we proceed with the test review? Or will you apply modifications, based on the feedback Guatebus gave you?

**Comment by olivernoguera** [comment]
Hi guatebus & Fernando,

Sorry for my later answer.I am on holidays  abroad.

Thanks for your answers. I fixed some things in last commit.
I have finished the pull. Should you proceed to review test.

Thanks a lot,

Oliver Noguera

**Comment by FernandoAbogado** [comment]
Thanks Oliver.
We'll review it as soon as possible... but just don't count on it for this week, as there are more request on the pipeline right now.

**Comment by LordKhizir** [comment]
Hi Oliver,
I just sent you an email with feedback.

**Pull request closed without merging**
