### PR TITLE
Questions?

### PR DESCRIPTION
**Pull request by alexandremq**
Hi!

I have couple questions about the requirements and the initial code:
1- Some of the requirements talk about "user" as if it were the publisher. Is a "user" the same as a "publisher" ?

2- In the requirement about listing tweets in descending order according to publication date, I am currently showing the publication date in the resulting list of tweets, is that correct or or I should keep the same number of fields displayed initially in the API ? The same question applies for the list of discarded tweets.

3- In a swagger specification query string parameters are not used as part of the path. Is it allowed to use query string parameters for the API "/discarded" ?

4- About the link shortener requirement, is there any internal library doing that, should I code my own algorithm to do that or can I call an external service to do that ? Could you give an example of url and the expected shortened version if it?

I look forward to hearing from you,

Alexandre

### CODE REVIEW

**Comment by LordKhizir** [comment]
Hi Alexandre,
I'll try to nail down the first two questions... and leave 3 and 4 for my colleagues.

1. - There are no different "roles". All tweets are published and consumed by users. A "Publisher" is a way to identify the user who actually published a tweet.
2. - You should respect the API contract.

**Comment by guatebus** [comment]
Hi Alexandre, replying to questions 3 and 4,

3. The request format to the `/discarded` endpoint is clear from the requirements doc. I recommend that you revise it again: https://github.com/scm-spain/ms-fc--backend-test#apis (a clue to look for is the `content-type` requirement)

4. You may implement this feature as you best see fit; the requirement is to not add any more libraries to the project. I recommend you review this requirement again, it seems you may have misunderstood it, as there is no mention of a 'link shortener'.

Hope this helps and, as always, questions are welcome.

**Comment by alexandremq** [comment]
Hi Tony, 

I have finished the test and pushed my changes. 

I look forward your feedback and I am opened to answer any question you might have.

Best regards,

Alexandre

**Comment by FernandoAbogado** [comment]
Thanks Alexandre!
We'll start reviewing this tomorrow, and keep you informed.

**Comment by alexandremq** [comment]
Awesome, thank you!

**Pull request closed without merging**
